# Generated by Django 4.2.9 on 2024-05-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
