# Generated by Django 4.2.9 on 2024-06-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0003_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
