# Generated by Django 4.2.9 on 2024-07-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0005_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diameter',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='externalnoiselevel',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
