# Generated by Django 4.2.9 on 2024-04-05 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0006_tires_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('tires', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tires.tires')),
            ],
        ),
    ]
